#!/bin/bash
# Script to push code to GitHub
# Auto-generated by Replit Agent

echo "🔧 Configuring GitHub remote..."
git remote set-url origin https://Bwreck9:${GITHUB_TOKEN}@github.com/Bwreck9/GiftXzalted.git

echo "📤 Pushing to GitHub..."
git push -u origin main

echo "✅ Done! Your code is now on GitHub."
